// <auto-generated />
using System;
using AspLessons;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspLessons.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251120133157_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspLessons.Favor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("FavorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("favor_name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_favors");

                    b.ToTable("favors", (string)null);
                });

            modelBuilder.Entity("AspLessons.Master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_masters");

                    b.ToTable("masters", (string)null);
                });

            modelBuilder.Entity("AspLessons.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FavorId")
                        .HasColumnType("integer")
                        .HasColumnName("favor_id");

                    b.Property<int>("MasterId")
                        .HasColumnType("integer")
                        .HasColumnName("master_id");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("register_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_registers");

                    b.HasIndex("FavorId")
                        .HasDatabaseName("ix_registers_favor_id");

                    b.HasIndex("MasterId")
                        .HasDatabaseName("ix_registers_master_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_registers_user_id");

                    b.ToTable("registers", (string)null);
                });

            modelBuilder.Entity("AspLessons.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AspLessons.WorkHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Begin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("begin");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end");

                    b.HasKey("Id")
                        .HasName("pk_work_hours");

                    b.ToTable("work_hours", (string)null);
                });

            modelBuilder.Entity("FavorMaster", b =>
                {
                    b.Property<int>("FavorsId")
                        .HasColumnType("integer")
                        .HasColumnName("favors_id");

                    b.Property<int>("MastersId")
                        .HasColumnType("integer")
                        .HasColumnName("masters_id");

                    b.HasKey("FavorsId", "MastersId")
                        .HasName("pk_favor_master");

                    b.HasIndex("MastersId")
                        .HasDatabaseName("ix_favor_master_masters_id");

                    b.ToTable("favor_master", (string)null);
                });

            modelBuilder.Entity("MasterWorkHours", b =>
                {
                    b.Property<int>("MastersId")
                        .HasColumnType("integer")
                        .HasColumnName("masters_id");

                    b.Property<int>("WorkHoursId")
                        .HasColumnType("integer")
                        .HasColumnName("work_hours_id");

                    b.HasKey("MastersId", "WorkHoursId")
                        .HasName("pk_master_work_hours");

                    b.HasIndex("WorkHoursId")
                        .HasDatabaseName("ix_master_work_hours_work_hours_id");

                    b.ToTable("master_work_hours", (string)null);
                });

            modelBuilder.Entity("AspLessons.Register", b =>
                {
                    b.HasOne("AspLessons.Favor", "Favor")
                        .WithMany()
                        .HasForeignKey("FavorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registers_favors_favor_id");

                    b.HasOne("AspLessons.Master", "Master")
                        .WithMany("Registers")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registers_masters_master_id");

                    b.HasOne("AspLessons.User", "User")
                        .WithMany("Registers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registers_users_user_id");

                    b.Navigation("Favor");

                    b.Navigation("Master");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FavorMaster", b =>
                {
                    b.HasOne("AspLessons.Favor", null)
                        .WithMany()
                        .HasForeignKey("FavorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favor_master_favors_favors_id");

                    b.HasOne("AspLessons.Master", null)
                        .WithMany()
                        .HasForeignKey("MastersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favor_master_masters_masters_id");
                });

            modelBuilder.Entity("MasterWorkHours", b =>
                {
                    b.HasOne("AspLessons.Master", null)
                        .WithMany()
                        .HasForeignKey("MastersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_work_hours_masters_masters_id");

                    b.HasOne("AspLessons.WorkHours", null)
                        .WithMany()
                        .HasForeignKey("WorkHoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_work_hours_work_hours_work_hours_id");
                });

            modelBuilder.Entity("AspLessons.Master", b =>
                {
                    b.Navigation("Registers");
                });

            modelBuilder.Entity("AspLessons.User", b =>
                {
                    b.Navigation("Registers");
                });
#pragma warning restore 612, 618
        }
    }
}
